language: node_js
node_js: "stable"
services: 
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CQZeDCjVyVf3tA0li/bZo9H3QtwLTFHOP6wENigWldbXaPPkOuaXoynqXoo1ycq3LpiJte3lamqmOzd10l/7zYCD22DLfa56E5OuMMksCAf9DXJh+pQlMg9ghZ+IAO0Z55/8TrFpRT+/ODe+UaSKBYW8fuqNsCrr3G6IpLXLre0N9ubWUNQQcMKGfpcRTdMti+gP40t6WUT50rIBZLSNI6TddAklFzOIXqSUct/h3aY3iuabQEI/DmTdGwKtFP43WXn6AWIWi50gjPooOdGK4wB93d+NZFWXHu6esUDWw7xvcdwMSGMrW/rV3ZWSr5KCVpn7LfKO9RKXbpn/HfVK/meNJ2Xjwtv7HUjipzntbLQN71b6lzVQGbLh6gr7WdhJtuXj4qT57aVhN0ToWBUDJOndWeR2mXDFM4tUERsgHQ79VYjjTgtG+y40ADchhjlVU3KzYx0gCXo6B4kG6M/PM2Wi2EOCr6BeD08ZoOAXb3tpfemfpBIsvWNP77cunn6IylWXekCeZIMD5YQ0WyihcQd6RnnoxDhJ4yyg6Ij9X9ugFGxdBGiG1TJ7rRGJj3pdugL507p7LJ8fiHCngv6kSTNSuvlH2uR1+h7dCIMnZx8dRAiwygAKDwn8S1LJMyhUV6/FbvvxStQLWr22/yXU2MUe/MAg9h3J0XdYfC5DaFg=
  app: pacific-temple-77586
  on:
    repo: richigro/Sell-App
