language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: JwvcugYKHO40qwNY9OvxGhk++PfcZEsxPGyP3tIPPzOEbLaF4/YIVrtIG94RuiCLmnFWa5oVEZcpT2BtwiZJmaOARecFX/PPyOl4zroNl/dNKU1/vy+rEuDh4LBIr9kAKHqwnIqGKAjKVKkXgHj2VBYkzKGaGrs/RJgAVaWYjFxX8aPxpMViXN2XOmGt+mm6YQOs2EHdz+r2EaGX7ioKPMuR8AqUmGPDczSmWUTHvcqHKIXYdpPQbZqHDtWMfnPez98wKCD+9TefX071E03B7c3hVNSoTEJzjEHwJE7tnWKMCpWtbYoAHVydNbPZBaXLabFmqlIt02xibFAXcHqH4TmrybRD9KJDEpnSC1fX/Ssh5fIMd2xMnYdd7aUWfy+byvt/4EEEeVX5m8lTvFsTJ/RqX5ENaXNP4lyumHI19AJ1fv0GamIunm10aD3bfNZP8qIvG1e9KTENgeF3SyRcSGN3apQjcBAOsyP9YMk6n6ww2+eDejZwiR1i1HPqL27jWi1nzTLrvPaduFaBGSrxWG1e2+I4wEq6xJkS+REWb30kwtLoGgfISU0ESNKw6K8XOyUw5x23CIkpF4jT6fc85FTPxS3m2dVLtajCqTFaoU/9xMWrdu8UvghCI3HbLrH6xDubq0LQXsyu0GfniDSbHHJvVIeanXT+HPRzChIV5JA=
  app: pacific-temple-77586
  on:
    repo: richigro/Sell-App
